FROM python:3.9.14-slim-buster

COPY . /searchengine

WORKDIR /searchengine

ARG AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY

ARG AWS_DEFAULT_REGION

ARG AWS_DATABASE_HOST

ARG AWS_DATABASE_USERNAME

ARG AWS_DATABASE_PASSWORD

ARG AWS_DATABASE_NAME

ARG AWS_DATABASE_TABLE

ARG AWS_BUCKET_NAME

ARG AWS_BUCKET_HEADER_URL

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID

ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

ENV AWS_DATABASE_HOST $AWS_DATABASE_HOST

ENV AWS_DATABASE_USERNAME $AWS_DATABASE_HOST

ENV AWS_DATABASE_PASSWORD $AWS_DATABASE_PASSWORD

ENV AWS_DATABASE_NAME $AWS_DATABASE_NAME

ENV AWS_DATABASE_TABLE $AWS_DATABASE_TABLE

ENV AWS_BUCKET_NAME $AWS_BUCKET_NAME

ENV AWS_BUCKET_HEADER_URL $AWS_BUCKET_HEADER_URL

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8000

CMD ["python","app.py"]